import { IBlogPost } from './all';

export const HowToWriteSoftware: IBlogPost = {
  slug: 'how-to-write-software',
  title: "How to Make Software When You Don't Know How to Code",
  date: '2021-11-19',
  excerpt:
    'As the resident software engineer amongst my friends, I get asked all the time for advice on how to bring their ideas into the real world. The good news is there’s more options than ever, but the nuances between them are important to understand before jumping into development.',
  link:
    'https://onepager.vc/blog/how-to-make-software-when-youre-not-technical',
  isExternal: true,
};

export const ElevateFounderDiversity: IBlogPost = {
  slug: 'step-to-elevate',
  title: 'A Step to Elevate the Diversity of Founders',
  date: '2021-10-08',
  excerpt:
    'The lack of diversity among venture backed founders is immediately visible to anyone working within the startup ecosystem. Despite studies showing the superior effectiveness of diverse groups and the issues that have stemmed from startups built around homogeneous teams, the lack of diversity among founders has barely shifted in the last decade.',
  link: 'https://onepager.vc/blog/a-step-to-elevate-the-diversity-of-founders',
  isExternal: true,
};

export const IntroducingLowTechAI: IBlogPost = {
  slug: 'introducing-lowtechai',
  title: 'LowTech AI: Simple AI Tools for Everyone',
  date: '2023-06-07',
  excerpt:
    'Our Mission: Simplify powerful AI systems to help more people harness their abilities and improve their work and lives.',
  link: 'https://lowtech.ai/blog/lowtech-ai-simple-ai-tools-for-everyone',
  isExternal: true,
};

export const HideYourPrompt: IBlogPost = {
  slug: 'Hide your prompt',
  title: 'Hide Your Prompt: A Better UX for Sharing Simple AI Tools',
  date: '2023-06-23',
  excerpt:
    'Using ChatGPT effectively is an acquired skill. Without prior experience and learned intuition, your AI generated responses will probably be improperly formatted, way too long, a bit cold in tone, or simply not what you were hoping for.',
  link:
    'https://lowtech.ai/blog/hide-your-prompt-a-better-ux-for-sharing-simple-ai-tools',
  isExternal: true,
};

export const WhatAreLLMs: IBlogPost = {
  slug: 'whats-a-large-language-model',
  title: `What’s a Large Language Model?`,
  date: '2023-09-30',
  excerpt:
    'If you’ve encountered text written by a computer in the past year (you definitely have), it was probably generated by a large language model, AKA an LLM.',
  link: 'https://lowtech.ai/blog/whats-a-large-language-model',
  isExternal: true,
};

export const PromptAThonV0: IBlogPost = {
  slug: 'recap-prompt-a-thon-v0',
  title: `Recap: Prompt-a-thon v0`,
  date: '2023-10-13',
  excerpt:
    'Today in Cambridge MA, we brought together a brilliant group of MIT MBA and PhD students to learn about AI prompting and build tools for LowTech AI.',
  link: 'https://lowtech.ai/blog/prompt-a-thon-v0',
  isExternal: true,
};
